version: '3.8'

x-apiserver-common: &apiserver-common
  image: dr.big.wtf/apiserver
  environment:
    RAILS_ENV: production
    APISERVER_DATABASE_HOST: postgres
    APISERVER_DATABASE_USERNAME: postgres
    APISERVER_DATABASE_PASSWORD: password

services:
  postgres:
    image: postgres:14
    environment:
      PGDATA: "/pgdata"
      POSTGRES_PASSWORD: password
    deploy:
      replicas: 1
    volumes:
      - postgres:/pgdata

  redis:
    image: redis:7
    deploy:
      replicas: 1

  web:
    <<: *apiserver-common
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3002:3000"
    deploy:
      replicas: 4
    command: bundle exec rails server -b 0.0.0.0

  sidekiq:
    <<: *apiserver-common
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 12
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  postgres: