version: '3.8'

x-rails-common: &rails-common
  image: dr.big.wtf/apiserver
  environment:
    RAILS_ENV: production
    APISERVER_DATABASE_USERNAME: postgres
    APISERVER_DATABASE_PASSWORD: password
    APISERVER_DATABASE_HOST: postgres
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:14-alpine
    environment:
      PGDATA: "/pgdata"
      POSTGRES_PASSWORD: password
    deploy:
      replicas: 1
    volumes:
      - postgres:/pgdata

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1

  web:
    <<: *rails-common
    build: .
    ports:
      - "3002:3000"
    deploy:
      replicas: 4
    command: bundle exec rails server -b 0.0.0.0

  sidekiq:
    <<: *rails-common
    deploy:
      replicas: 12
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  postgres:
