default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>

development:
  <<: *default
  database: apiserver_development
  #username: ApiServer
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: apiserver_test

production:
  <<: *default
  database: apiserver
  username: bigwtf
  password: <%= Rails.application.credentials.database_password! %>
  host: 127.0.0.1
