default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: apiserver_development
  #username: ApiServer
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: apiserver_test

production:
  <<: *default
  host: <%= ENV["APISERVER_DATABASE_HOST"] %>
  port: 5432
  database: apiserver
  username: <%= ENV["APISERVER_DATABASE_USERNAME"] %>
  password: <%= ENV["APISERVER_DATABASE_PASSWORD"] %>
